version: 2
jobs:
  docker_build:
    machine: true
    steps:
      - checkout
      - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS
         docker build -t arcticf0x/flask_cicd .
         docker push arcticf0x/flask_cicd

  k8_deploy_stg:
    machine: true
    steps:
      - checkout
      - run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
      - run: |
          scp -r rancher@$VULTR_STG_NODE1:/home/rancher/.kube/config ${HOME}/config
      - run: |
          sed -ie "s/updated_timestamp/$(date)/g" deployment/flask_cicd.yaml
          kubectl --kubeconfig=${HOME}/config apply -f deployment/flask_cicd.yaml
         
  # k8_deploy_stg:
  #   docker:
  #     - image: google/cloud-sdk
  #   steps:
  #     - checkout
  #     - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
  #     - run: |
  #         gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
  #         gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
  #         gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
  #         gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
  #         sed -ie "s/updated_timestamp/$(date)/g" deployment/flask_cicd.yaml
  #         kubectl apply -f deployment/flask_cicd.yaml
workflows:
  version: 2
  rolling_update:
    jobs:
      - docker_build
      - k8_deploy_stg:
          requires:
            - docker_build
          filters:
            branches:
              only:
                - k8