version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS
      # build the application image
      - run: docker build -t $DOCKER_USER/flask_cicd .
      # deploy the image
      - run: docker push $DOCKER_USER/flask_cicd
      # for now, lets set the kubeconfig ourselves
      - run: mkdir -p .kube/config && mv /.circleci/kubeconfig /root/.kube/config
      # ensure we have kubectl
      - run: ./deployment/ensure_kubectl.sh https://45.76.19.58:6443
      - deploy:
          name: Rolling update
          command: |
            kubectl apply -f deployment/flask_cicd.yaml
