version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS
      # build the application image
      - run: docker build -t $DOCKER_USER/flask_cicd .
      # deploy the image
      - run: docker push $DOCKER_USER/flask_cicd
      # for now, lets set the kubeconfig ourselves
      - run: mkdir -p ~/.kube && mv .circleci/kubeconfig ~/.kube/config
      # ensure we have kubectl
      - run: |
          if [ ! -e ~/.kube/kubectl ]; then
              cd ~/.kube
              wget https://storage.googleapis.com/kubernetes-release/release/v1.9.1/bin/linux/amd64/kubectl
              chmod +x ~/.kube/kubectl
          fi
      - deploy:
          name: Rolling update
          command: |
            sed -ie "s/THIS_STRING_IS_REPLACED_DURING_BUILD/$(date)/g" deployment/flask_cicd.yaml
            ~/.kube/kubectl apply -f deployment/flask_cicd.yaml
