version: 2
jobs:
  docker_build:
    machine: true
    steps:
      - checkout
      - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS
         docker build -t arcticf0x/flask_cicd .
         docker push arcticf0x/flask_cicd
  swarm_deploy:
    branches:
      only:
        - master
    machine: true
    steps:
      - run: |
          ssh root@swarm-manager-west-0.iogamemaker.com 'docker service update --image arcticf0x/flask_cicd be_cicd'
         
  # k8_deploy_stg:
  #   docker:
  #     - image: google/cloud-sdk
  #   steps:
  #     - checkout
  #     - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
  #     - run: |
  #         gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
  #         gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
  #         gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
  #         gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
  #         sed -ie "s/updated_timestamp/$(date)/g" deployment/flask_cicd.yaml
  #         kubectl apply -f deployment/flask_cicd.yaml
workflows:
  version: 2
  rolling_update:
    jobs:
      - docker_build
      - swarm_deploy:
          requires:
            - docker_build
          filters:
            branches:
              only:
                - master