version: 2
jobs:
  docker_build:
    machine: true
    steps:
      branches:
        only:
          - k8
      - checkout
      - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS
         docker build -t $DOCKER_USER/flask_cicd .
         docker push $DOCKER_USER/flask_cicd
  k8_deploy:
    docker:
      - image: azuresdk/azure-cli-python:2.0.23
    steps:
      - run: |
         az login -u $AZURE_USER -p $AZURE_PASSWORD
         az aks get-credentials -g stagingK8s -n stagingK8s
         az aks install-cli
         sed -ie "s/updated_timestamp/$(date)/g" deployment/flask_cicd.yaml
         kubectl apply -f deployment/flask_cicd.yaml
workflows:
  version: 2
  rolling_update:
    jobs:
      - docker_build
      - k8_deploy:
          requires:
            - docker_build