version: 2
jobs:
  build-job:
    machine: true
    steps:
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application image
      - run: docker build -t arcticf0x/flask_cicd .

      # deploy the image
      - run: docker push arcticf0x/flask_cicd