apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-cicd
  labels:
    app: flask-cicd
    tier: backend
spec:
  selector:
    matchLabels:
      app: flask-cicd
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-cicd
        tier: backend
    spec:
      containers:
      - name: flask-cicd
        image: arcticf0x/flask_cicd
        imagePullPolicy: Always
        env:
        - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
          value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
